### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by erikvanbrakel** [erikvanbrakel/terraform-provider-sumologic#19]
When _something_ goes wrong, the current error messages don't really point you in any direction. In general, it just complains about JSON format or something....

**Comment by erikvanbrakel** [comment]
Fixed. In the future, I need to pay more attention to not ignoring errors returned by libraries.

**Comment by shinitiandrei** [comment]
@erikvanbrakel me again 😅 
I've been looking through your updates to find what I'm doing is in accordance and it seems that I am doing right. 
I've entered this topic because I'm getting this message:
`* sumologic_collector.collector: unexpected end of JSON input`

Which seems that my binary is a bit behind from your commits as you mentioned here 
> In general, it just complains about JSON format or something....
And well, for example, the attribute "**category**" from Collector is still **mandatory**, as it is not in your current code.
Therefore could you please check and update the release page, please? :) 
So far you've done a great job here! Thanks again!

**Comment by erikvanbrakel** [comment]
That's right. I'm not tagging every single change. Actually, there's no real strategy on when I tag something, haha. I'll make a release now :+1:

**Comment by shinitiandrei** [comment]
Haha all good, I just tested it and the error also changed 😆 
Thanks heaps for your continuous and quick support!
